[workspace]
channels = ["conda-forge"]
name = "DiffusionDPO"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
accelerate = "==0.20.2"
diffusers = "==0.20.0"
torchvision = "*"
transformers = "==4.30.2"
datasets = "*"
ftfy = "*"
tensorboard = "*"
jinja2 = "*"
bitsandbytes = "*"
xformers = "==0.0.22"
hpsv2 = "*"
openai-clip = "==1.0.1"
numpy = "<2"
huggingface_hub = "<0.26.0"
pysocks = ">=1.7.1, <2"

[system-requirements]
cuda = "12"
