[workspace]
channels = ["conda-forge"]
name = "DiffusionDPO"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
# accelerate = "==0.20.2"
accelerate = "==1.10.0"
diffusers = "==0.35.0"
torchvision = "*"
torch = ">=2.2"
# transformers = "==4.30.2"
transformers = "==4.57.0"
datasets = "<3.7.0"
ftfy = "*"
tensorboard = "*"
jinja2 = "*"
bitsandbytes = "*"
xformers = "==0.0.30"
hpsv2x = "*"
openai-clip = "==1.0.1"
numpy = "<2"
huggingface_hub = "<0.35.0"
pysocks = ">=1.7.1, <2"

pudb = "*"

[system-requirements]
cuda = "12"
